name: zcli-action
description: Github Action to deploy Zendesk Apps using ZCLI.
inputs:
  env:
    description: "Environment"
    required: true
    default: "dev"
  path:
    description: "Path to dist directory"
    required: true
    default: "apps/zendesk/dist"
  milliseconds:
    description: "milliseconds"
    required: true
    default: 1000

runs:
  using: "node16"
  main: "dist/index.js"
